version: 0.0
os: linux
files:
  - source: /
    destination: /home/kmh/CodeDeployGitHubDemo
permissions:
  - object: /home/kmh
    pattern: "CodeDeployGitHubDemo"
    owner: kmh
    group: kmh
  # - object: /home/kmh/CodeDeployGitHubDemo
    # owner: kmh
    # group: kmh
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/create_dir.sh
      timeout: 3
      runas: kmh